language:
    - python

python:
    - "3.3"

env:
    # Note: clang not support libc++
    - CONFIG="Release" TOOLCHAIN="gcc-4-8"
    - CONFIG="Debug" TOOLCHAIN="clang-libstdcxx"

install:
    # install clang 3.2 and gcc 4.8
    #     * github.com/travis-ci-tester/travis-test-clang-3.2
    #     * github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
    - sudo apt-get update
    - sudo apt-get install g++-4.8
    - sudo apt-get install cmake
    - sudo apt-get install libcurl3-dev
    # -- end

    # install cmake toolchains and script
    - POLLY_VERSION="0.6.2"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export PATH="`pwd`/polly-${POLLY_VERSION}/bin:${PATH}"
    # -- end
    # install cmake
    - CMAKE_VERSION="3.2.1-ruslo"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    -   build.py --install --toolchain default --config Release --fwd "CMAKE_USE_SYSTEM_CURL=YES"
    -   export PATH="`pwd`/_install/default/bin:${PATH}"
    - cd ..
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end

script:
    # Note: clang not support libc++
    - build.py --test --verbose --toolchain ${TOOLCHAIN} --config ${CONFIG} --fwd CPP-NETLIB_URI_BUILD_TEST=ON HUNTER_RUN_INSTALL=ON
